button:
  enable: false
  row1:
  - label: Home
    url: https://home.example.com
embed:
  author:
    icon: ''
    name: ''
  color: 5865F2
  description: Next update {{time}}
  fields:
    inline: false
  footer:
    icon: ''
    text: PteroServerStats by @HirziDevs
  image: ''
  thumbnail: ''
  timestamp: true
  title: Server Stats
log_error: false
message:
  attachment: ''
  content: ''
notifier:
  embed:
    author:
      icon: ''
      name: ''
    footer:
      icon: ''
      text: PteroServerStats Notifier
    image: ''
    thumbnail: ''
    timestamp: true
  enable: false
  webhook: ''
presence:
  enable: true
  status: online
  text: Server
  type: watching
refresh: 10
server:
  cpu: true
  details: true
  disk: true
  memory: true
  network: true
  uptime: true
server_ids:
- 7e2a2d5d-ecee-44ba-b6a9-2bc8cca59fa9
- 807c016e-8d25-4852-a83b-b977754846fc
status:
  offline: ':red_circle: Offline'
  online: ':green_circle: Online'
timeout: 5
version: 1
